INSERT INTO T_DRIVER (ID, FIRST_NAME, SURNAME) VALUES (111, 'Peter', 'Westlin');
INSERT INTO T_DRIVER (ID, FIRST_NAME, SURNAME) VALUES (222, 'David', 'Coulthard');
INSERT INTO T_DRIVER (ID, FIRST_NAME, SURNAME) VALUES (333, 'Peter', 'Popovic');
