registrationserver:
  image: kartingtimes-registrationserver
  ports:
    - "1111:1111"

driversserver:
  image: kartingtimes-driversserver
  ports:
    - "2222:2222"
  environment:
    SPRING_PROFILES_ACTIVE: docker-linking
  links:
    - registrationserver

trackserver:
  image: kartingtimes-trackserver
  ports:
    - "3333:3333"
  environment:
    SPRING_PROFILES_ACTIVE: docker-linking
  links:
    - registrationserver

laptimesserver:
  image: kartingtimes-laptimesserver
  ports:
    - "4444:4444"
  environment:
    SPRING_PROFILES_ACTIVE: docker-linking
  links:
    - registrationserver

webserver:
  image: kartingtimes-webserver
  ports:
    - "8080:8080"
  environment:
    SPRING_PROFILES_ACTIVE: docker-linking
  links:
    - registrationserver
    - driversserver
    - trackserver
    - laptimesserver
