# Spring properties
spring:
  application:
     name: laptimes-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory
                             # Template location for this application only

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 10
    registryFetchIntervalSeconds: 10
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 10

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port

spring.jackson.serialization.INDENT_OUTPUT: true


---

spring:
    profiles: docker-linking

eureka:
  client:
    serviceUrl:
      defaultZone: http://registrationserver:1111/eureka/
