# Configure this Discovery Server
eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0
    responseCacheUpdateIntervalMs: 10
    registrySyncRetries: 0    # 0 for development, NOT production!
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 10
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    instanceInfoReplicationIntervalSeconds: 10
    initialInstanceInfoReplicationIntervalSeconds: 10


server:
  port: 1111   # HTTP (Tomcat) port

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf

spring.jackson.serialization.INDENT_OUTPUT: true

